---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  user: vagrant
  sudo: yes
  tasks:
  - name: ensure apache & php are installed
    apt: pkg={{ item }} state=present
    with_items:
      - apache2
      - php5
      - libapache2-mod-php5
      - php5-mysql
      - php5-tidy
      - php5-curl
      - imagemagick
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=apache2 state=started
  - name: ensure MySQL is installed
    apt: pkg={{ item }} state=present
    with_items:
      - mysql-server
      - python-mysqldb
  - name: Start the MySQL service
    service: name=mysql state=started
  - name: create db 'reason'
    mysql_db: db=reason state=present
  # WARNING!: usernames and passwords should not be specified here for production!
  - name: create user reason_user...NO PRODUCTION PASSWORDS
    mysql_user: state=present name=reason_user password=some_password priv=reason.*:ALL
  - name: create symlink for reason_4.0/www/ to /var/www/reason
    file: src=/var/reason/reason_4.0/www/ dest=/var/www/reason owner=www-data group=www-data state=link
  - name: create symlink for www/ to /var/www/reason_package
    file: src=/var/reason/www/ dest=/var/www/reason_package owner=www-data group=www-data state=link
  - name: create symlink for thor/ to /var/www/thor
    file: src=/var/reason/thor/ dest=/var/www/thor owner=www-data group=www-data state=link
  - name: set permissions on write required dirs
    file: path={{ item }} group=www-data mode=0774
    with_items:
      - /var/reason/reason_4.0/data/csv_data/
      - /var/reason/reason_4.0/data/logs/
      - /var/reason/reason_4.0/data/assets/
      - /var/reason/reason_4.0/data/images/
      - /var/reason/reason_4.0/data/tmp/
      - /var/reason/reason_4.0/data/cache/
      - /var/www/reason/tmp/
      - /var/reason/reason_4.0/data/geocodes/
  - name: copy php.ini to /etc/php5/apache2/php.ini
    copy: src=php.ini dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644
    notify:
    - restart apache
  - name: copy reason config files for vagrant
    copy: src={{ item }} dest=/vagrant/settings/{{ item }}
    with_items:
      - dbs.xml
      - error_handler_settings.php
  - name: copy apache config with rewrite FileInfo
    copy: src=default dest=/etc/apache2/sites-available/default owner=root group=root mode=0644
    notify:
    - restart apache
  - name: Apache enable rewrite
    command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
    notify: 
    - restart apache
  - name: Write initial database data
    command: sh /vagrant/provisioning/init_dbs.sh creates=/home/vagrant/dbs_written
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
