---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  user: vagrant
  sudo: yes
  tasks:
  - name: ensure apache & php are installed
    apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
    with_items:
      - apache2
      - php5
      - libapache2-mod-php5
      - php5-mysql
      - php5-tidy
      - php5-curl
      - imagemagick
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=apache2 state=started
  - name: ensure MySQL is installed
    apt: pkg={{ item }} state=present
    with_items:
      - mysql-server
      - python-mysqldb
  - name: Start the MySQL service
    service: name=mysql state=started
  - name: create reason databases
    mysql_db: db={{ item }} state=present
    with_items:
      - reason
    notify: import reason databases
  # WARNING!: usernames and passwords should not be specified here for production!
  - name: create user reason_user...NO PRODUCTION PASSWORDS
    mysql_user: state=present name=reason_user password=some_password priv=reason.*:ALL

  - name: create reason symlinks
    file: src={{ item.src }} dest={{ item.dest }} owner=www-data group=www-data state=link
    with_items:
      - { src: '/var/reason/reason_4.0/www/', dest: '/var/www/reason' }
      - { src: '/var/reason/www/', dest: '/var/www/reason_package' }
      - { src: '/var/reason/thor/', dest: '/var/www/thor' }
      - { src: '/var/reason/loki_2.0/', dest: '/var/www/loki_2.0' }
      - { src: '/var/reason/flvplayer/', dest: '/var/www/flvplayer' }
      - { src: '/var/reason/jquery/', dest: '/var/www/jquery' }
      - { src: '/var/reason/date_picker/', dest: '/var/www/date_picker' }

  - name: set permissions on write required dirs
    file: path={{ item }} group=www-data mode=0774 state=directory recurse=yes
    with_items:
      - /var/www/
      - /var/reason/reason_4.0/data/
  - name: copy php.ini to /etc/php5/apache2/php.ini
    copy: src=php.ini dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644
    notify:
    - restart apache
  - name: copy reason config files for vagrant
    copy: src={{ item }} dest=/vagrant/settings/{{ item }}
    with_items:
      - dbs.xml
      - error_handler_settings.php
  - name: copy apache config with rewrite FileInfo
    copy: src=default dest=/etc/apache2/sites-available/default owner=root group=root mode=0644
    notify:
    - restart apache
  - name: Apache enable rewrite
    command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
    notify: 
    - restart apache
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
    - name: import reason databases
      mysql_db: db={{ item.db }} target={{ item.target }} state=import
      with_items:
        - { db: reason, target: /vagrant/reason_4.0/data/dbs/reason4.4.sql }

